[tool.poetry]
name = "fastapi-mongodb"
version = "0.2.0"
description = ""
authors = ["Jakub Miazek <the@grillazz.com>"]
readme = "README.md"
packages = [{include = "fastapi_mongodb"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
motor = "^3.3.2"
uvicorn = "^0.24.0"
pytest-cov = "^4.1.0"
httpx = "^0.25.1"
rich = "^13.7.0"
black = "^23.11.0"
isort = "^5.12.0"
pydantic-settings = "^2.1.0"
uvloop = "^0.19.0"
httptools = "^0.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
