[tool.poetry]
name = "fastapi-mongodb"
version = "0.4.0"
description = ""
authors = ["Jakub Miazek <the@grillazz.com>"]
readme = "README.md"
packages = [{ include = "fastapi_mongodb" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.2"
pydantic = { version = "2.6.1", extras = ["email"] }
pydantic-settings = "2.2.0"
motor = "^3.3.2"
uvicorn = { version = "0.27.1", extras = ["standard"] }
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
httpx = "^0.26.0"
rich = "^13.7.0"
black = "^24.2.0"
isort = "^5.12.0"
uvloop = "^0.19.0"
httptools = "^0.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
