[tool.poetry]
name = "fastapi-mongodb"
version = "0.4.0"
description = ""
authors = ["Jakub Miazek <the@grillazz.com>"]
readme = "README.md"
packages = [{ include = "fastapi_mongodb" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.1"
pydantic = { version = "2.6.4", extras = ["email"] }
pydantic-settings = "2.2.1"
motor = "^3.4.0"
uvicorn = { version = "0.29.0", extras = ["standard"] }
pytest = "^8.1.1"
pytest-cov = "^5.0.0"
httpx = "^0.27.0"
rich = "^13.7.1"
black = "^24.3.0"
isort = "^5.12.0"
uvloop = "^0.19.0"
httptools = "^0.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
